# Generated by Django 2.2.3 on 2019-07-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField()),
                ('Modified_at', models.DateTimeField()),
                ('Complete_by', models.DateTimeField()),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed')], default=0)),
                ('Is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'to_do_list',
            },
        ),
    ]
