# Generated by Django 2.2.3 on 2019-07-20 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='Created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='Modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
