# Generated by Django 2.2.3 on 2019-07-20 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_auto_20190720_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='Created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='Modified_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
